name: Build and push docker images

on:
  push:
    branches:    
      - master

jobs:
  base:
    name: Base
    runs-on: ubuntu-18.04
    steps:
    - name: Check out code
      uses: actions/checkout@v2.3.2

    - name: Build & push base image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: alvisisme/dev-container
        tags: base
        registry: docker.io
        dockerfile: containers/base/Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
  node:
    name: Node
    runs-on: ubuntu-18.04
    needs: base
    steps:
    - name: Check out code
      uses: actions/checkout@v2.3.2

    - name: Build & push node image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: alvisisme/dev-container
        tags: node
        registry: docker.io
        dockerfile: containers/node/Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
  java:
    name: Java
    runs-on: ubuntu-18.04
    needs: base
    steps:
    - name: Check out code
      uses: actions/checkout@v2.3.2

    - name: Build & push java image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: alvisisme/dev-container
        tags: java
        registry: docker.io
        dockerfile: containers/java/Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
  python:
    name: Python
    runs-on: ubuntu-18.04
    needs: base
    steps:
    - name: Check out code
      uses: actions/checkout@v2.3.2

    - name: Build & push python image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: alvisisme/dev-container
        tags: python
        registry: docker.io
        dockerfile: containers/python/Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
  c:
    name: C
    runs-on: ubuntu-18.04
    needs: base
    steps:
    - name: Check out code
      uses: actions/checkout@v2.3.2

    - name: Build & push c image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: alvisisme/dev-container
        tags: c
        registry: docker.io
        dockerfile: containers/c/Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
  cpp:
    name: Cpp
    runs-on: ubuntu-18.04
    needs: base
    steps:
    - name: Check out code
      uses: actions/checkout@v2.3.2

    - name: Build & push cpp image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: alvisisme/dev-container
        tags: cpp
        registry: docker.io
        dockerfile: containers/cpp/Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}